#!/bin/bash
# vim: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

iam="$(basename "$0")"
mode=help
ERR_MSG='not_valid'

function show_help() {
    cat <<_HELP

Usage::
    "$iam" -c <string>: Check string if it is valid as ip address.
    "$iam" -s <ip address> -n N : Return next N address.
    "$iam" -h         : Show this message.

_HELP
}

function check_address() {
    local addr="$1"
    local type="$2"
    local IFS=.
    if ! [[ ("$addr" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$) ]]; then
        echo "$ERR_MSG"
        exit 1
    fi

    # shellcheck disable=SC2206
    local n=($addr)
    if [ "${n[0]}" -lt 0 ] \
        || [ "${n[1]}" -lt 0 ] \
        || [ "${n[2]}" -lt 0 ] \
        || [ "${n[3]}" -lt 0 ] \
        || [ "${n[0]}" -gt 255 ] \
        || [ "${n[1]}" -gt 255 ] \
        || [ "${n[2]}" -gt 255 ] \
        || [ "${n[3]}" -gt 255 ]; then
        echo "$ERR_MSG"
        exit 1
    fi
    if [ "${type:-ip}" = dec ]; then
        printf "%s\n" $(((\
        n[0] << 24) | (\
        n[1] << 16) | (\
        n[2] << 8) | (\
        n[3])))
    else
        echo "$addr"
    fi
}

function calc_address() {
    dec="$(($1 + $2))"
    check_address "$(
        printf "%d.%d.%d.%d\n" \
            $((dec >> 24)) \
            $(((dec >> 16) & 0xFF)) \
            $(((dec >> 8) & 0xFF)) \
            $((dec & 0xFF))
    )"
}

if [ $# = 0 ]; then
    show_help
    exit 1
fi

while getopts c:hn:s: sw; do
    case $sw in
        c)
            mode=check
            addr="${OPTARG}"
            ;;
        s)
            mode=calc
            dec_addr="$(check_address "${OPTARG}" "dec")"
            if [ "$dec_addr" = "$ERR_MSG" ]; then
                mode=help
            fi
            ;;
        n)
            mode=calc
            if ! [[ ("$OPTARG" =~ ^[1-9][0-9]*$) ]]; then
                mode=help
            else
                num="${OPTARG}"
            fi
            ;;
        *)
            mode=help
            ;;
    esac
done

case $mode in
    check)
        check_address "${addr}"
        ;;
    calc)
        if [ -z "$dec_addr" ] || [ -z "$num" ]; then
            show_help
        else
            calc_address "${dec_addr}" "${num}"
        fi
        ;;
    help)
        show_help
        ;;
esac
