#!/bin/bash

mode="$1"
case ${mode:=stream} in
    stream)
        mode=stream
        ;;
    show)
        mode=show
        #startdate="--start $( date +%F )"
        #enddate="--end $( date +%F )"
        ;;
    *)
        echo "$0 show|stream"
        exit 0
        ;;
esac

sudo log "$mode" --style syslog --info \
    --predicate '(processImagePath contains "smtp") || (processImagePath contains "qmgr") || (processImagePath contains "pickup") || (processImagePath contains "cleanup") || (processImagePath contains "trivial-rewrite")'
