#!/bin/bash

function _readlink(){
    c="$1"
    f="$( basename "$c" )"
    if [ "$( type -a "$c" 2> /dev/null | head -1 )"x = x ]; then
        d="$( cd "$(dirname "$c")" || exit 1; pwd )"
    else
        p="$( type -a "$c" | head -1 | awk '{$1="";$2=""; print $0}'| sed 's/^[ \t]*//' )"
        d="$( dirname "$p" )"
    fi
    if [ -L "${d}/${f}" ]; then
        cd "${d}" || exit 1
        r="$( readlink -n "${d}/${f}" )"
        _readlink "$r"
    else
        echo "${d}/${f}"
    fi
}

fullpath_to_me="$( _readlink "$0" )"
pathtome="$( dirname "$fullpath_to_me" )"
if [ "$( whoami )" != root ]; then doAsRoot='sudo' ; fi

# tls
if [ -x "$mailservername" ]; then
    mailservername="$( hostname )"
fi
if [ -f "$tlsca" ] && [ -f "$tlscert" ] && [ -f "$tlskey" ]; then
   tls_enabled=yes
else
    if [ -f "/etc/letsencrypt/live/${mailservername}/cert.pem" ] && \
       [ -f "/etc/letsencrypt/live/${mailservername}/fullchain.pem" ] && \
       [ -f "/etc/letsencrypt/live/${mailservername}/privkey.pem" ] ; then
        tlscert="/etc/letsencrypt/live/${mailservername}/cert.pem"
        tlsca="/etc/letsencrypt/live/${mailservername}/fullchain.pem"
        tlskey="/etc/letsencrypt/live/${mailservername}/privkey.pem"
        tls_enabled=yes
        chgrp certusers /etc/letsencrypt/{archive,live,keys}
        chmod 750 /etc/letsencrypt/{archive,live,keys}
    fi
fi

##--- TEST
tls_enabled=yes
tlsca=/usr/local/etc/certificates/Local-ROOTCA.pem
tlscert=/usr/local/etc/certificates/pms01.vmnet3.com.pem
tlskey=/usr/local/etc/certificates/pms01.vmnet3.com.np.key
##--- TEST


# postfix
$doAsRoot "${pathtome}/setup-postfix"

# dovecot
IsDovecot="$( brew info dovecot | grep "Not installed" )"
if [ "$IsDovecot" = "Not installed" ]; then
    cat <_MEG
install with homebrew
    brew install dovecot --with-pigeonhole
_MSG
    exit 1
fi
$doAsRoot "${pathtome}/setup-dovecot"
