#!/bin/bash

function _readlink(){
    c="$1"
    f="$( basename "$c" )"
    if [ "$( type -a "$c" 2> /dev/null | head -1 )"x = x ]; then
        d="$( cd "$(dirname "$c")" || exit 1; pwd )"
    else
        p="$( type -a "$c" | head -1 | awk '{$1="";$2=""; print $0}'| sed 's/^[ \t]*//' )"
        d="$( dirname "$p" )"
    fi
    if [ -L "${d}/${f}" ]; then
        cd "${d}" || exit 1
        r="$( readlink -n "${d}/${f}" )"
        _readlink "$r"
    else
        echo "${d}/${f}"
    fi
}

fullpath_to_me="$( _readlink "$0" )"
pathtome="$( dirname "$fullpath_to_me" )"
if [ "$( whoami )" != root ]; then doAsRoot='sudo' ; fi

# postfix
$doAsRoot "${pathtome}/setup-postfix"

# dovecot
$doAsRoot "${pathtome}/setup-dovecot"
