#!/bin/bash

function _readlink(){
    c="$1"
    f=$( basename "$c" )
    if [ "$( type -a "$c" 2> /dev/null | head -1 )x" = x ]; then
        d="$( cd "$(dirname "$c")" || exit 1 ; pwd )"
    else
        p="$( type -a "$c" | head -1 | awk '{$1="";$2=""; print $0}' | sed 's/^[ \t]*//' )"
        d="$( dirname "$p" )"
    fi
    if [ -L "${d}/${f}" ]; then
        cd "${d}" || exit 1
        r="$( readlink -n "${d}/${f}" )"
        _readlink "$r"
    else
        echo "${d}/${f}"
    fi
}

fullpath_to_me=$( _readlink "$0" )
pathtome=$( dirname "$fullpath_to_me" )
PREVIOUSCONFDIR="/Library/Server/Mail/Config/dovecot"
CONFDIR="/usr/local/etc/dovecot"
LIBEXECDIR="/usr/local/libexec/dovecot"
CONF="${CONFDIR}/dovecot.conf"
OWNERID="$( stat -f "%u:%g" "$CONFDIR" )"
backupdate="$( date +%Y%m%d-%H%M%S )"
#default_internal_group=_dovecot
#default_internal_user=_dovecot
#default_login_user=_dovenull
# _dovecot g- mail
# _dovenull g- _dovenull

if [ -d "$PREVIOUSCONFDIR" ]; then
    mv "${CONFDIR}" "${CONFDIR}.backup.at.$backupdate"
    mkdir -p "${CONFDIR}"
    cp -a "${PREVIOUSCONFDIR}"/* "${CONFDIR}"/
fi

for f in "${CONFDIR}"/conf.d/*
do
    sed -i -e "s#${PREVIOUSCONFDIR}#$CONFDIR#g" "$f"
    sed -i -e "s#/Applications/Server.app/Contents/ServerRoot/usr/libexec/dovecot#$LIBEXECDIR#g" "$f"
    sed -i -e "s#/Library/Logs/Mail#/usr/local/var/log/dovecot#g" "$f"
done
sed -i -e "s/^aps_topic/#aps_topic/g" "$CONF"
rm -f "${CONFDIR}/conf.d/*-e" "${CONF}-e"
chown -R "$OWNERID" "${CONFDIR}"
ln -fhs /usr/local/var/log/dovecot /var/log/dovecot

: $LIBEXECDIR
mkdir -p "$LIBEXECDIR"
cp "${pathtome}/additional-scripts/quota-exceeded.sh" "$LIBEXECDIR"
cp "${pathtome}/additional-scripts/quota-warning.sh" "$LIBEXECDIR"

: Start daemon
# brew services start dovecot

#       /usr/local/etc/dovecot/dovecot.conf
#              Dovecot's main configuration file.
#
#       /usr/local/etc/dovecot/dovecot-ldap.conf.ext
#              Dovecot's LDAP authdb/userdb module configuration file.
#
#       /usr/local/etc/dovecot/dovecot-sql.conf.ext
#              Dovecot's SQL authdb/userdb module configuration file.
#
#       /usr/local/etc/dovecot/dovecot-dict-sql.conf.ext
#              Dovecot's dict configuration with SQL-backend.
#
#       /usr/local/etc/dovecot/conf.d/auth-*-conf.ext
#              Configuration files of different authentication modules.
#
#       /usr/local/etc/dovecot/conf.d/*.conf
#              Configuration files of different services and settings.
