#!/bin/bash

function _readlink(){
    c="$1"
    f=`basename "$c"`
    if [ "`type -a "$c" 2> /dev/null| head -1`"x = x ]; then
        d=`cd $(dirname "$c"); pwd`
    else
        p=`type -a "$c" | head -1 | awk '{$1="";$2=""; print $0}'| sed 's/^[ \t]*//'`
        d=`dirname "$p"`
    fi
    if [ -L "${d}/${f}" ]; then
        cd "${d}"
        r="`readlink -n \"${d}/${f}\"`"
        _readlink "$r"
    else
        echo "${d}/${f}"
    fi
}

fullpath_to_me=`_readlink "$0"`
pathtome=$(dirname "$fullpath_to_me")

launchdplist="${pathtome}/../LaunchDaemons/org.postfix.master.plist"
queuedir=$(/usr/libexec/PlistBuddy -c "print QueueDirectories:0" "$launchdplist")
confdir=$(/usr/libexec/PlistBuddy -c "print ProgramArguments:2" "$launchdplist")
spooldir=$(dirname $queuedir)

mkdir -p "$confdir"
if [ -d /Library/Server/Mail/Config/postfix ]; then
    cp -an /Library/Server/Mail/Config/postfix/* "$confdir" > /dev/null
else
    cp -an /etc/postfix/* "$confdir" > /dev/null
fi

mkdir -p "$spooldir"
for d in active bounce corrupt defer deferred flush hold incoming maildrop pid private public saved trace
do
    mkdir -m 700 -p "${spooldir}/$d"
    chown _postfix:wheel "${spooldir}/$d"
done
chown _postfix:_postdrop "${spooldir}/maildrop"
chown _postfix:_postdrop "${spooldir}/public"
chown root:wheel "${spooldir}/pid"
chmod 730 "${spooldir}/maildrop"
chmod 710 "${spooldir}/public"
chmod 755 "${spooldir}/pid"

exit 0

if [ -f /Library/LaunchDaemons/org.postfix.master.plist ]; then
    mv /Library/LaunchDaemons/org.postfix.master.plist \
        /Library/LaunchDaemons/org.postfix.master.plist.$$.previous 
fi

cp "${lauchdplist}" /Library/LaunchDaemons/org.postfix.master.plist
