#!/bin/bash
#-
#- Set up postfix on macOS
#- Usage:
#-     sudo setup-postfix
#-
#-
#-


function _readlink(){
    c="$1"
    f=`basename "$c"`
    if [ "`type -a "$c" 2> /dev/null| head -1`"x = x ]; then
        d=`cd $(dirname "$c"); pwd`
    else
        p=`type -a "$c" | head -1 | awk '{$1="";$2=""; print $0}'| sed 's/^[ \t]*//'`
        d=`dirname "$p"`
    fi
    if [ -L "${d}/${f}" ]; then
        cd "${d}"
        r="`readlink -n \"${d}/${f}\"`"
        _readlink "$r"
    else
        echo "${d}/${f}"
    fi
}

fullpath_to_me=`_readlink "$0"`
pathtome=$(dirname "$fullpath_to_me")
launchdplist="${pathtome}/../LaunchDaemons/org.postfix.master.plist"
queuedir=$(/usr/libexec/PlistBuddy -c "print QueueDirectories:0" "$launchdplist")
confdir=$(/usr/libexec/PlistBuddy -c "print ProgramArguments:2" "$launchdplist")
spooldir=$(dirname $queuedir)

: Prepare and convert config files
mkdir -p "$confdir"
if [ -d /Library/Server/Mail/Config/postfix ]; then
    cp -an /Library/Server/Mail/Config/postfix/* "$confdir" > /dev/null
else
    cp -an /etc/postfix/* "$confdir" > /dev/null
fi

postconf -c "$confdir" -e "alias_database = hash:${confdir}/aliases"
postconf -c "$confdir" -e "alias_maps = hash:${confdir}/aliases"
postconf -c "$confdir" -e "config_directory = ${confdir}"
postconf -c "$confdir" -e "daemon_directory = /usr/libexec/postfix"
postconf -c "$confdir" -e "header_checks = pcre:${confdir}/custom_header_checks"
postconf -c "$confdir" -e "html_directory = /usr/share/doc/postfix"
postconf -c "$confdir" -e "imap_submit_cred_file = ${confdir}/submit.cred"
postconf -c "$confdir" -e "mailq_path = /usr/bin/mailq"
postconf -c "$confdir" -e "manpage_directory = /usr/share/man"
postconf -c "$confdir" -e "newaliases_path = /usr/bin/newaliases"
postconf -c "$confdir" -e "queue_directory = $spooldir"
postconf -c "$confdir" -e "readme_directory = /usr/share/doc/postfix"
postconf -c "$confdir" -e "recipient_canonical_maps = hash:${confdir}/system_user_maps"
postconf -c "$confdir" -e "sample_directory = /usr/share/doc/postfix/examples"
postconf -c "$confdir" -e "sendmail_path = /usr/sbin/sendmail"
postconf -c "$confdir" -e "virtual_alias_domains = hash:${confdir}/virtual_domains"
postconf -c "$confdir" -e "virtual_alias_maps = hash:${confdir}/virtual_users"

: Prepare spool directories
mkdir -p "$spooldir"
for d in active bounce corrupt defer deferred flush hold incoming maildrop pid private public saved trace
do
    mkdir -m 700 -p "${spooldir}/$d"
    chown _postfix:wheel "${spooldir}/$d"
done
chown _postfix:_postdrop "${spooldir}/maildrop"
chown _postfix:_postdrop "${spooldir}/public"
chown root:wheel "${spooldir}/pid"
chmod 730 "${spooldir}/maildrop"
chmod 710 "${spooldir}/public"
chmod 755 "${spooldir}/pid"

: Prepare Launchd.plist
if [ -f /Library/LaunchDaemons/org.postfix.master.plist ]; then
    backupdate=$(date +%Y%m%d-%H%M%S)
    mv /Library/LaunchDaemons/org.postfix.master.plist \
        /Library/LaunchDaemons/org.postfix.master.plist.backup.at.$backupdate
fi

cp "${launchdplist}" /Library/LaunchDaemons/org.postfix.master.plist
chown 0:0 /Library/LaunchDaemons/org.postfix.master.plist
chmod 644 /Library/LaunchDaemons/org.postfix.master.plist
